name: Security Scan
on:
  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r .

      - name: Check Bandit Output
        run: |
          if bandit -r . | grep -q "high"; then
            echo "Block"
            exit 1
          else
            echo "Successful"
          fi

      - name: Auto-merge if successful
        if: success()
        uses: pascalgn/automerge-action@v0.15.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

