name: Security Scan

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Python)
        run: pip install bandit

      - name: Run Bandit security scan (Python)
        run: bandit -r . -f json -o bandit_report.json || true

      - name: Analyze Results
        run: |
          python .github/scripts/analyze_results.py
